samples:
  - sample_id: "FS43706397"
    kinship: "proband"
    status: "affected"
    sex: "NA"
    code: 1
    bam: "/g/data/kr68/projects/wgs_test/FS43706397/pipeface-dev/20241011-175841/FS43706397.hg38.minimap2.whatshap.sorted.haplotagged.bam"
    coverage: "/g/data/kr68/projects/wgs_test/FS43706397/pipeface-dev/20241011-175841/FS43706397.hg38.depth.tsv"

paths:
  snvs_vcf: "/g/data/kr68/projects/wgs_test/FS43706397/pipeface-dev/20241011-175841/FS43706397.hg38.deepvariant.snp_indel.phased.annotated.vcf.gz"
  svs_vcf: "/g/data/kr68/projects/wgs_test/FS43706397/pipeface-dev/20241011-175841/FS43706397.hg38.sniffles.sv.phased.vcf.gz"
  rdata_output: "/g/data/kr68/andre/puzzleapp_test/FS43706397.rdata"

dependencies:
  panel_app: "/g/data/kr68/andre/AMAMAL_PKD/Annotations/all_panel_app.tsv"
  vep_consequences: "/g/data/kr68/andre/AMAMAL_PKD/Annotations/vep_annotations.tsv"
  phenotype_data: "/g/data/kr68/andre/AMAMAL_PKD/Annotations/phenotype_to_genes.txt"

