# Configuration file for the Shiny app
# record for panelapp database dir location
panelapp_db_dir = "/g/data/if89/testdir/puzzleapp/db/panelapp"
# record for phenotype database dir location
phenotype_db_dir = "/g/data/if89/testdir/puzzleapp/db/phenotype"
# record for VEP consequences database dir location (this is within the package extdata directory)
vep_consequences_db_dir = "extdata/db/vep_consequences"
