# Configuration file for the Shiny app
# record for panelapp database dir location
panelapp_db_dir = "/g/data/if89/testdir/puzzleapp/db/panelapp"
# record for phenotype database dir location
phenotype_db_dir = "/g/data/if89/testdir/puzzleapp/db/phenotype"
# record for VEP consequences database dir location (this is within the package extdata directory)
vep_consequences_db_dir = "extdata/db/vep_consequences"
# IGV custom genome location
igv_custom_genome_id="hg38.analysisSet"
igv_custom_genome_name="hg38.analysisSet"
igv_custom_genome_fasta="/g/data/kr68/genome/hg38.analysisSet.fa"
igv_custom_genome_index="/g/data/kr68/genome/hg38.analysisSet.fa.fai"
